[package]
name = "ufire_iso_ec"
version = "0.9.0"
authors = ["uFire <contact@gmail.com>"]
readme = "README.md"
description = "Measure Electrical Conductivity, Total Dissolved Solids, and Salinity"
license = "MIT"
keywords = ["ec", "electrical", "conductivity", "sensor", "salinity"]

[lib]
name = "ufire_iso_ec"
path = "src/lib.rs"

[[bin]]
name = "ufire_ec_bin"
path = "src/main.rs"

[dependencies]
i2cdev = "0.3.2"
byteorder = "1"
shrust = "0.0.6"
